apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app
spec:
  replicas: 1 # ensure (at least) 1 pod is always running
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
      - name: crypto-app
        image: my-first-app
        imagePullPolicy: Never  # Tells K8s to use the image we just built locally
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-service
spec:
  type: NodePort
  selector:
    app: crypto-app
  ports:
    - port: 80
      targetPort: 8000